# ----------------------------------------------------------------------
# Copyright (c) 2021, 2022 Oracle and/or its affiliates. All rights reserved.
# The Universal Permissive License (UPL), Version 1.0
# ----------------------------------------------------------------------

# Create a service account for in-cluster operations/automation
apiVersion: v1
kind: ServiceAccount
metadata:
  name: turn-svc-account
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: turn-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "patch", "update"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["create", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: turn-role-binding
subjects:
  - kind: ServiceAccount
    name: turn-svc-account
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: turn-role
  apiGroup: rbac.authorization.k8s.io